[package]
name = "game"
version = "0.1.0"
authors = ["roal_yr"]
edition = "2018"


[dependencies]
colored = "2.0"
#serde = { version = "1.0", features = ["derive"]  }
toml = "0.5"
bincode = "1.3"


coords = { path = "../../libs/coords" }
units = { path = "../../libs/units" }
codec = { path = "../../libs/codec" }
constants_app = { path = "../../libs/constants_app" }
constants_world = { path = "../../libs/constants_world" }
io_ops = { path = "../../libs/io_ops" }
text_ops = { path = "../../libs/text_ops" }
prng = { path = "../../libs/prng" }
path = { path = "../../libs/path" }
#floodfill = { path = "../../libs/floodfill" }






